'''Autogenerated dummy package module anabling code completion in Python editors
 MODO Build #621568
'''

class BasicItemBehaviors:
    def add(self, item):
        pass

    def after_load(self, item):
        pass

    def doomed(self, item):
        pass

    def loading(self, item):
        pass

    def newborn(self, item, original, flags):
        pass

    def parent_ok(self, item, parent):
        pass

    def remove(self, item):
        pass

    def synth_name(self, item):
        pass



class BasicPackage:
    def __init__(self):
        self.acts = NoneType()

    def pkg_Attach(self):
        pass

    def pkg_CollectItems(self, collection, mode):
        pass

    def pkg_PostLoad(self, scene):
        pass

    def pkg_SetupChannels(self, addChan):
        pass

    def pkg_TestInterface(self, guid):
        pass



class BasicPackageInstance:
    def pins_Add(self):
        pass

    def pins_AfterLoad(self):
        pass

    def pins_Cleanup(self):
        pass

    def pins_Doomed(self):
        pass

    def pins_DupType(self):
        pass

    def pins_Initialize(self, item, super):
        pass

    def pins_Loading(self):
        pass

    def pins_Newborn(self, original, flags):
        pass

    def pins_Remove(self):
        pass

    def pins_SynthName(self):
        pass

    def pins_TestParent(self, item):
        pass



class DefaultPackage:
    def pkg_Attach(self):
        pass

    def pkg_CollectItems(self, collection, mode):
        pass

    def pkg_PostLoad(self, scene):
        pass

    def pkg_SetupChannels(self, addChan):
        pass

    def pkg_TestInterface(self, guid):
        pass



class DefaultPackageInstance:
    def pins_Add(self):
        pass

    def pins_AfterLoad(self):
        pass

    def pins_Cleanup(self):
        pass

    def pins_Doomed(self):
        pass

    def pins_DupType(self):
        pass

    def pins_Initialize(self, item, super):
        pass

    def pins_Loading(self):
        pass

    def pins_Newborn(self, original, flags):
        pass

    def pins_Remove(self):
        pass

    def pins_SynthName(self):
        pass

    def pins_TestParent(self, item):
        pass



