'''Autogenerated dummy utils module anabling code completion in Python editors
 MODO Build #621568
'''

class ItemType:
    def __init__(self):
        self._code = NoneType()
        self._name = NoneType()

    def code(self):
        pass

    def name(self):
        pass

    def set(self, name):
        pass



class ThreadBody:
    def __init__(self):
        self.t_S = lx.service.Thread()



def decodeID4(val):
    pass

def item_type(name):
    pass

def lxID4(tagID):
    pass

